# Generated by Django 3.1 on 2020-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_twitter_url', models.URLField(null=True)),
                ('project_twitter_image', models.URLField(null=True)),
            ],
        ),
    ]
