# Generated by Django 3.1 on 2020-08-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_youtube_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='youtube_url',
            new_name='youtube_embed_url',
        ),
    ]
