from django.db import models


class Lesson(models.Model):
    # id is generated by Django by default...explicit id isn't required.
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    content = models.TextField()

    BEGINNER = 'beginner'
    INTERMEDIATE = 'intermediate'
    ADVANCED = 'advanced'
    LEVEL = [
        (BEGINNER, ('Beginner')),
        (INTERMEDIATE, ('Intermediate')),
        (ADVANCED, ('Advanced')),
    ]

    level = models.CharField(max_length=60, choices=LEVEL, default=BEGINNER)

    def __str__(self):
        return self.title
