# Generated by Django 3.1 on 2020-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('bite_type', models.CharField(choices=[('fundamental', 'Fundamental'), ('technical', 'Technical')], default='fundamental', max_length=60, verbose_name='bite type')),
            ],
        ),
    ]
