# Generated by Django 3.1 on 2020-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bites', '0004_auto_20200818_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bite',
            name='author_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
